sudo: required
services:
  - docker

branches:
  only:
    - deploy-test

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in deploy_key.enc -out deploy_key -d
  - eval 'ssh-agent -s'
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'bash ./deploy.sh'
