sudo: required
services:
  - docker

branches:
  only:
    - deploy-test

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in deploy_key.enc -out deploy_key -d
  - eval 'ssh-agent -s'
  - chmod 600 deploy_key
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $SERVER_IP 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts
  - ssh-add deploy_key

install:
  - ssh $SERVER_USER@$SERVER_IP 'mkdir hello'
