sudo: required
services:
  - docker

branches:
  only:
  - deploy-test

before_install:
  - docker build -t $DOCKER_ID/test -f ./Dockerfile.dev .

script:
  - docker run $DOCKER_ID/test npm test -- --coverage

after_success:
  - docker build -t $DOCKER_ID/uc-app .
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/uc-app
  - sudo apt-get update
  - sudo apt-get install sshpass
  - sshpass -p "$SERVER_PW" ssh $SERVER_HOST 'bash -s' < ./deploy.sh
