sudo: required
services:
  - docker

branches:
  only:
  - deploy-test

addons:
  ssh_known_hosts:
  - $SERVER_IP

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - ssh $SERVER_USER@$SERVER_IP 'mkdir hello'
