version: '3'
services:
  client:
    image: 'kenjifam/uc-app'
    restart: always
    volumes:
      - /root/certs:/etc/nginx/certs
      - /root/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'